---
- name: firewall | ufw | Start ufw service
  ansible.builtin.service:
    name: ufw
    enabled: true
    state: started

- name: firewall | ufw | Enable ufw
  community.general.ufw:
    direction: incoming
    state: enabled
    policy: allow

- name: firewall | ufw | Enable forwarding
  ansible.builtin.lineinfile:
    dest: /etc/default/ufw
    regexp: "^DEFAULT_FORWARD_POLICY="
    line: DEFAULT_FORWARD_POLICY="ACCEPT"

- name: firewall | ufw | Allow incoming VPN connections
  community.general.ufw:
    direction: in
    proto: "{{ openvpn_proto }}"
    to_port: "{{ openvpn_port | string }}"
    rule: allow

- name: firewall | ufw | Accept packets from VPN tunnel adaptor
  community.general.ufw:
    direction: in
    interface: tun0
    rule: allow

- name: firewall | ufw | Setup SNAT table rules
  when: openvpn_no_nat is falsy and openvpn_masquerade_not_snat is falsy
  notify:
    - Restart ufw
  block:
    - name: firewall | ufw | Setup IPv4 SNAT rules
      ansible.builtin.blockinfile:
        dest: /etc/ufw/before.rules
        state: present
        insertbefore: \*filter
        block: |
          # OpenVPN config
          *nat
          :POSTROUTING ACCEPT [0:0]
          -A POSTROUTING -s {{ openvpn_server_network }}/{{ openvpn_server_netmask_cidr }} ! -d {{ openvpn_server_network }}/{{ openvpn_server_netmask_cidr }} -j SNAT --to-source {{ openvpn_lan_source_ip }}
          COMMIT

    - name: firewall | ufw | Setup IPv6 SNAT rules
      ansible.builtin.blockinfile:
        dest: /etc/ufw/before6.rules
        state: present
        insertbefore: \*filter
        block: |
          # OpenVPN config
          *nat
          :POSTROUTING ACCEPT [0:0]
          -A POSTROUTING -s {{ openvpn_server_ipv6_network }} ! -d {{ openvpn_server_ipv6_network }} -j SNAT --to-source {{ ansible_default_ipv6.address }}
          COMMIT
      when: openvpn_server_ipv6_network is defined

- name: firewall | ufw | Setup NAT with MASQUERADE
  when: openvpn_masquerade_not_snat is truthy and openvpn_no_nat is falsy
  notify:
    - Restart ufw
  block:
    - name: firewall | ufw | Setup IPv4 NAT with MASQUERADE
      ansible.builtin.blockinfile:
        dest: /etc/ufw/before.rules
        state: present
        insertbefore: \*filter
        block: |
          # OpenVPN config
          *nat
          :POSTROUTING ACCEPT [0:0]
          -A POSTROUTING -s {{ openvpn_server_network }}/{{ openvpn_server_netmask_cidr }} ! -d {{ openvpn_server_network }}/{{ openvpn_server_netmask_cidr }}  -j MASQUERADE
          COMMIT
    - name: firewall | ufw | Setup IPv6 NAT with MASQUERADE
      ansible.builtin.blockinfile:
        dest: /etc/ufw/before6.rules
        state: present
        insertbefore: \*filter
        block: |
          # OpenVPN config
          *nat
          :POSTROUTING ACCEPT [0:0]
          -A POSTROUTING -s {{ openvpn_server_ipv6_network }} ! -d {{ openvpn_server_ipv6_network }}  -j MASQUERADE
          COMMIT
      when: openvpn_server_ipv6_network is defined
