---
- name: selinux | Allow OpenVPN port (semanage)
  community.general.seport:
    ports: "{{ openvpn_port }}"
    proto: "{{ openvpn_proto }}"
    setype: openvpn_port_t
    state: present
  when:
    - ansible_facts['selinux']['status'] == 'enabled'

- name: selinux | Remove legacy module artifacts
  when:
    - ansible_facts['selinux']['status'] == 'enabled'
  block:
    - name: selinux | Check if legacy module is loaded
      ansible.builtin.command: semodule --list-modules
      register: __semodule_loaded
      changed_when: false

    - name: selinux | Remove legacy module
      ansible.builtin.command: semodule -r {{ openvpn_selinux_module }}
      when: __semodule_loaded.stdout.find(openvpn_selinux_module) != -1
      changed_when: true

    - name: selinux | Remove legacy module files
      ansible.builtin.file:
        path: "/var/lib/selinux/{{ item }}"
        state: absent
      loop:
        - "{{ openvpn_selinux_module }}.te"
        - "{{ openvpn_selinux_module }}.mod"
        - "{{ openvpn_selinux_module }}.pp"
