---
- name: selinux | Allow OpenVPN port (semanage)
  community.general.seport:
    ports: "{{ openvpn_port }}"
    proto: "{{ openvpn_proto }}"
    setype: openvpn_port_t
    state: present
  when:
    - ansible_facts['selinux']['status'] == 'enabled'
    - openvpn_selinux_use_semanage | bool

- name: selinux | Remove legacy module artifacts
  when:
    - ansible_facts['selinux']['status'] == 'enabled'
    - openvpn_selinux_use_semanage | bool
  block:
    - name: selinux | Check if legacy module is loaded
      ansible.builtin.command: semodule --list-modules
      register: __semodule_loaded
      changed_when: false

    - name: selinux | Remove legacy module
      ansible.builtin.command: semodule -r {{ openvpn_selinux_module }}
      when: __semodule_loaded.stdout.find(openvpn_selinux_module) != -1
      changed_when: true

    - name: selinux | Remove legacy module files
      ansible.builtin.file:
        path: "/var/lib/selinux/{{ item }}"
        state: absent
      loop:
        - "{{ openvpn_selinux_module }}.te"
        - "{{ openvpn_selinux_module }}.mod"
        - "{{ openvpn_selinux_module }}.pp"

- name: selinux | Legacy module method
  when:
    - ansible_facts['selinux']['status'] == 'enabled'
    - not openvpn_selinux_use_semanage | bool
  block:
    - name: selinux | Warn about deprecated module method
      ansible.builtin.debug:
        msg: "Using the custom SELinux module compilation method is deprecated and will be removed in a future version.
           Please switch to 'openvpn_selinux_use_semanage: true'."

    - name: selinux | Check if module was loaded
      ansible.builtin.command: semodule --list-modules
      register: __semodule_loaded
      changed_when: false

    - name: selinux | Setup policy
      when:
        - ansible_facts['selinux']['status'] == 'enabled'
        - __semodule_loaded.stdout.find(openvpn_selinux_module) == -1
      block:
        - name: selinux | Copy selinux type enforcement file
          ansible.builtin.template:
            src: "selinux_module.te.j2"
            dest: /var/lib/selinux/{{ openvpn_selinux_module }}.te
            mode: "0644"
        - name: selinux | Make sure selinux policy build RPM is installed
          ansible.builtin.package:
            name: checkpolicy
            state: present
        - name: selinux | Install selinux-policy-targeted-extra for RHEL 10 and variants
          ansible.builtin.package:
            name: selinux-policy-targeted-extra
            state: present
          when:
            - ansible_facts['os_family'] == "RedHat"
            - ansible_facts['distribution_major_version']|int >= 10
            - ansible_facts['distribution'] != "Fedora"
            # This RPM doesn't appear to exist on RHEL
            - ansible_facts['distribution'] != "RedHat"
        - name: selinux | Build and install selinux policy
          ansible.builtin.command: "{{ item }}"
          args:
            chdir: /var/lib/selinux
          with_items:
            - "checkmodule -M -m -o {{ openvpn_selinux_module }}.mod {{ openvpn_selinux_module }}.te"
            - "semodule_package -o {{ openvpn_selinux_module }}.pp -m {{ openvpn_selinux_module }}.mod"
            - "semodule -i {{ openvpn_selinux_module }}.pp"
          changed_when: true
